### ISSUE TITLE
registration redirect 404

### ISSUE THREAD

**Issue by SquirrelCall** [DaveLuhman/toolkeeper#292]
![{F97B4BE3-4BAE-49CC-AECB-567DC5BA1278}](https://github.com/user-attachments/assets/595a7f22-e3c2-4c87-ab4a-d0d6b8eda894)

**Comment by SquirrelCall** [comment]
![image](https://github.com/user-attachments/assets/46870538-2217-4494-b427-3e746df5f630)
![{E7DD97B2-E5B7-4D7B-B297-CF03A30B80AA}](https://github.com/user-attachments/assets/a52036ac-28f8-468d-8613-f4a769c8e5f8)
![{E5F4AC59-14DD-4B58-9CC1-AE7144F7731D}](https://github.com/user-attachments/assets/c430c397-d6b2-4563-81b4-5cfd687ce86b)
![{6A6D9936-E0FF-415F-93C6-BAF2169E070D}](https://github.com/user-attachments/assets/04236e94-5802-4833-bad7-3b332781e5e7)

**Comment by SquirrelCall** [comment]
Tried the register button

![{9747F38F-E036-4521-BFE6-2E385225BD90}](https://github.com/user-attachments/assets/0aa339b2-8a33-4263-adcc-71bc43fcee7a)

**Comment by DaveLuhman** [comment]
The post-payment modal was redirecting to the wrong site. I've fixed that, and your user is creating, but I can't determine why the product isn't being found. I've added logging to the JSON payload validation function, so I can see more details. 

Please give it another shot when you have time.

**Comment by SquirrelCall** [comment]
closer. haven't received an email to set up my password yet

![image](https://github.com/user-attachments/assets/7afe0bb6-be60-419b-bd1e-db0509b291b2)

**Comment by DaveLuhman** [comment]
I believe I found the problem.  There was an API key missing from the environment variables. I've redeployed the instance and cleared the prospects again.  Go ahead and test when you can.

**Comment by SquirrelCall** [comment]
No change

**Comment by DaveLuhman** [comment]
Email sent successfully
Successfully processed subscription_created webhook for subscription 723116

I've identified the issue. In the webhook payload, the event_name is in the "meta" object, but in the code we're trying to access it directly from the webhookPayload. This is causing the validation to fail. We need to update the validation logic to check for meta.event_name instead of event_name directly.

The change has been pushed and the webhook reset.   Please check your email for credentails.
