### ISSUE TITLE
Navigation in from dashboard.

### ISSUE THREAD

**Issue by SquirrelCall** [DaveLuhman/toolkeeper#293]
It would be helpful if the left hand navigation menu appeared on the dashboard too. 
![{68BD5215-C880-40FB-A559-A3047CF64F55}](https://github.com/user-attachments/assets/e8a811dd-3b74-4f59-9b4f-dc56ed9ae448)

**Comment by DaveLuhman** [comment]
These settings are only available to managers and above, with "Import" being available to Admins on any given tenant.  Due to that, and the limited screen space on mobile viewports, the settings sidebar will only be available from the settings pages. This keeps concerns separated properly and keeps auth for settings delineated on user/manager/admin lines.

**Comment by SquirrelCall** [comment]
Gotcha
