### ISSUE TITLE
Select multiple tools and change assignment

### ISSUE THREAD

**Issue by SquirrelCall** [DaveLuhman/toolkeeper#299]
It would be handy to select multiple tools and change their service assignment together.  idk if that's a real world use but I imported 1700+ tools and I don't know that I want to touch each individually.

**Comment by DaveLuhman** [comment]
the check-in/out button at the top of any screen allows you to select a service assignment or enter a job number and then fill a list of tools, using any of the three unique identifiers.  It will then audit the list and show their current assignments on a confirm page where you can confirm the change.

This is mostly designed around using a barcode scanner, so that one can scan the SA, then scan a list of tools from the printer-friendly report into the textarea.
